apiVersion: v1
kind: ConfigMap
metadata:
  name: varc-portal-config
  namespace: varc
data:
  PORT: "3099"
  NEXTAUTH_URL: "https://www.hamvn.com"
  NEXT_PUBLIC_SITE_URL: "https://www.hamvn.com"
  AUTH_URL: "https://www.hamvn.com"
  AUTH_TRUST_HOST: "true"
