apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: varc-portal
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: varc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: varc-portal
                port:
                  number: 80
